name: Java CI
on: [push]
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 
          jenkinsci/jfr-static-image-action@master
        with: 
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt
          jcasc: jcasc.yml
